## 1 常量

### 1.1 numpy.nan

In [1]:
import numpy as np

In [2]:
# 两个numpy.nan是不相等的
(np.nan == np.nan), (np.nan != np.nan)

(False, True)

In [3]:
x = np.array([1, 1, 8, np.nan, 10])
print(x)

y = np.isnan(x)
print(y)

z = np.count_nonzero(y)
print(z)

[ 1.  1.  8. nan 10.]
[False False False  True False]
1


### 1.2 numpy.inf

In [4]:
# Inf = inf = infty = Infinity = PINF

### 1.3 numpy.pi

In [7]:
np.pi

3.141592653589793

### 1.4 numpy.e

In [8]:
np.e

2.718281828459045

## 2 数据类型

### 2.1 常见数据类型

In [10]:
a = np.dtype('b1')
print(a.type)
print(a.itemsize)
a

<class 'numpy.bool_'>
1


dtype('bool')

In [12]:
a = np.dtype('i1')
print(a.type)
print(a.itemsize)
print(a)
print('--------')

a = np.dtype('i2')
print(a.type) 
print(a.itemsize)
print(a)
print('--------')

a = np.dtype('i4')
print(a.type)
print(a.itemsize)
print(a)
print('--------')

a = np.dtype('i8')
print(a.type)
print(a.itemsize)
print(a)

<class 'numpy.int8'>
1
int8
--------
<class 'numpy.int16'>
2
int16
--------
<class 'numpy.int32'>
4
int32
--------
<class 'numpy.int64'>
8
int64


In [14]:
a = np.dtype('u1')
print(a.type)
print(a.itemsize) 
a = np.dtype('u2')
print(a.type)
print(a.itemsize)
a = np.dtype('u4')
print(a.type)
print(a.itemsize)
a = np.dtype('u8')
print(a.type)
print(a.itemsize)

<class 'numpy.uint8'>
1
<class 'numpy.uint16'>
2
<class 'numpy.uint32'>
4
<class 'numpy.uint64'>
8


In [15]:
a = np.dtype('f2')
print(a.type)
print(a.itemsize)
a = np.dtype('f4')
print(a.type)
print(a.itemsize)
a = np.dtype('f8')
print(a.type)
print(a.itemsize)

<class 'numpy.float16'>
2
<class 'numpy.float32'>
4
<class 'numpy.float64'>
8


In [16]:
a = np.dtype('S')
print(a.type)
print(a.itemsize)
a = np.dtype('S3')
print(a.type)
print(a.itemsize)

<class 'numpy.bytes_'>
0
<class 'numpy.bytes_'>
3


In [17]:
a = np.dtype('U3')
print(a.type)
print(a.itemsize)

<class 'numpy.str_'>
12


In [18]:
ii16 = np.iinfo(np.int16)
print(ii16.min)
print(ii16.max)
ii32 = np.iinfo(np.int32)
print(ii32.min)
print(ii32.max)

-32768
32767
-2147483648
2147483647


In [19]:
ff16 = np.finfo(np.float16)
print(ff16.bits)
print(ff16.min)
print(ff16.max)
print(ff16.eps)
ff32 = np.finfo(np.float32)
print(ff32.bits)
print(ff32.min)
print(ff32.max)
print(ff32.eps)

16
-65500.0
65500.0
0.000977
32
-3.4028235e+38
3.4028235e+38
1.1920929e-07


## 3 时间日期和时间增量

### 3.1 datatime64 基础

In [20]:
# numpy 会根据字符串自动选择对应的单位
a = np.datetime64('2020-03-01')
print(a, a.dtype)
a = np.datetime64('2020-03')
print(a, a.dtype)
a = np.datetime64('2020-03-08 20:00:05')
print(a, a.dtype)
a = np.datetime64('2020-03-08 20:00')
print(a, a.dtype)
a = np.datetime64('2020-03-08 20')
print(a, a.dtype)

2020-03-01 datetime64[D]
2020-03 datetime64[M]
2020-03-08T20:00:05 datetime64[s]
2020-03-08T20:00 datetime64[m]
2020-03-08T20 datetime64[h]


In [21]:
# 强制指定单位的例子
a = np.datetime64('2020-03', 'D')
print(a, a.dtype)

a = np.datetime64('2020-03', 'Y')
print(a, a.dtype)

print(np.datetime64('2020-03') == np.datetime64('2020-03-01'))
print(np.datetime64('2020-03') == np.datetime64('2020-03-02'))

2020-03-01 datetime64[D]
2020 datetime64[Y]
True
False


In [22]:
# 创建数组时，统一化为最小的单位
a = np.array(['2020-03', '2020-03-08', '2020-03-08 20:00'], dtype='datetime64')
print(a, a.dtype)

['2020-03-01T00:00' '2020-03-08T00:00' '2020-03-08T20:00'] datetime64[m]


In [23]:
# arange() 用于生成日期范围
a = np.arange('2020-08-01', '2020-08-10', dtype=np.datetime64)
print(a)
print(a.dtype)

a = np.arange('2020-08-01 20:00', '2020-08-10', dtype=np.datetime64)
print(a)
print(a.dtype)

a = np.arange('2020-05', '2020-12', dtype=np.datetime64)
print(a)
print(a.dtype)

['2020-08-01' '2020-08-02' '2020-08-03' '2020-08-04' '2020-08-05'
 '2020-08-06' '2020-08-07' '2020-08-08' '2020-08-09']
datetime64[D]
['2020-08-01T20:00' '2020-08-01T20:01' '2020-08-01T20:02' ...
 '2020-08-09T23:57' '2020-08-09T23:58' '2020-08-09T23:59']
datetime64[m]
['2020-05' '2020-06' '2020-07' '2020-08' '2020-09' '2020-10' '2020-11']
datetime64[M]


### 3.2 datatime64 和 timedelta64 运算

In [24]:
# timedelta 用于计算两个 datatime64 之差，且其单位与datatime64中较小的一致
a = np.datetime64('2020-03-08') - np.datetime64('2020-03-07')
print(a, a.dtype)

b = np.datetime64('2020-03-08') - np.datetime64('202-03-07 08:00')
print(b, b.dtype)

# 可指定单位
c = np.datetime64('2020-03-08') - np.datetime64('2020-03-07 23:00', 'D')
print(c, c.dtype)

1 days timedelta64[D]
956178240 minutes timedelta64[m]
1 days timedelta64[D]


In [27]:
a = np.datetime64('2020-03') + np.timedelta64(20, 'D')
print(a, a.dtype)

b = np.datetime64('2020-06-15 00:00') + np.timedelta64(12, 'h')
print(b, b.dtype)

c = np.datetime64('2020-10-18 00:00') + np.timedelta64(14, 'h')
print(c, c.dtype)

2020-03-21 datetime64[D]
2020-06-15T12:00 datetime64[m]
2020-10-18T14:00 datetime64[m]


In [28]:
# 年（Y）和月（M）这两个单位无法和其它单位进行运算
a = np.timedelta64(1, 'Y')
b = np.timedelta64(a, 'M')
print(a)
print(b)

c = np.timedelta64(1, 'h')
d = np.timedelta64(c, 'm')
print(c)
print(d)

print(np.timedelta64(a, 'D')) # 报错
print(np.timedelta64(b, 'D')) # 报错

1 years
12 months
1 hours
60 minutes


TypeError: Cannot cast NumPy timedelta64 scalar from metadata [Y] to [D] according to the rule 'same_kind'

In [30]:
# timedelta64 运算
a = np.timedelta64(1, 'Y')
b = np.timedelta64(6, 'M')
c = np.timedelta64(1, 'W')
d = np.timedelta64(1, 'D')
e = np.timedelta64(10, 'D')

print(a)
print(b)
print(a + b)
print(a - b)
print(2 * a)
print(a / b)
print(c / d)
print(c % e)
print(c / e)

1 years
6 months
18 months
6 months
2 years
2.0
7.0
7 days
0.7


### datatime64 的应用

In [31]:
# busyday_offset
# 2020-07-10 星期五
a = np.busday_offset('2020-07-10', offsets=1)
print(a)

a = np.busday_offset('2020-07-11', offsets=1)
print(a)

2020-07-13


ValueError: Non-business day date in busday_offset

In [39]:
a = np.busday_offset('2020-07-10', offsets=-1)
print(a)

a = np.busday_offset('2020-07-10', offsets=0)
print(a)

a = np.busday_offset('2020-07-10', offsets=2)
print(a)

2020-07-09
2020-07-10
2020-07-14


In [40]:
a = np.busday_offset('2020-07-11', offsets=0, roll='forward')
b = np.busday_offset('2020-07-11', offsets=0, roll='backward')
print(a)
print(b)

2020-07-13
2020-07-10


In [41]:
a = np.busday_offset('2020-07-11', offsets=1, roll='forward')
b = np.busday_offset('2020-07-11', offsets=1, roll='backward')
print(a)
print(b)

2020-07-14
2020-07-13


In [43]:
# is_busyday
a = np.is_busday('2020-07-10')
b = np.is_busday('2020-07-11')
print(a)
print(b) 

True
False


In [44]:
# 统计工作天数
begindates = np.datetime64('2020-07-10')
enddates = np.datetime64('2020-07-20')
a = np.arange(begindates, enddates, dtype='datetime64')
b = np.count_nonzero(np.is_busday(a))
print(a)
print(b)

['2020-07-10' '2020-07-11' '2020-07-12' '2020-07-13' '2020-07-14'
 '2020-07-15' '2020-07-16' '2020-07-17' '2020-07-18' '2020-07-19']
6


In [45]:
# 自定义周掩码值，即指定一周中哪些星期是工作日。
# 2020-07-10 星期五
a = np.is_busday('2020-07-10', weekmask=[1, 1, 1, 1, 1, 0, 0])
b = np.is_busday('2020-07-10', weekmask=[1, 1, 1, 1, 0, 0, 1])
print(a)
print(b)

True
False


In [46]:
# busyday_count()
begindates = np.datetime64('2020-07-10')
enddates = np.datetime64('2020-07-20')
a = np.busday_count(begindates, enddates)
b = np.busday_count(enddates, begindates)
print(a)
print(b)

6
-6


## 4 数组的创建

### 4.1 （a）依据现有数据创建ndarray

In [48]:
# 创建一维数组
a = np.array([0, 1, 2, 3, 4])
print(a, type(a))

# 创建二维数组
b = np.array([[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20],
[21, 22, 23, 24, 25],
[26, 27, 28, 29, 30],
[31, 32, 33, 34, 35]])
print(b, type(b))

# 创建三维数组
c = np.array([[(1.5, 2, 3), (4, 5, 6)],
[(3, 2, 1), (4, 5, 6)]])
print(c, type(c))

[0 1 2 3 4] <class 'numpy.ndarray'>
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]] <class 'numpy.ndarray'>
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]] <class 'numpy.ndarray'>


### (b)通过asarray() 函数进行创建

In [49]:
# array() 和 asarray() 都可以将结构数据转化为 ndarray，但是 array() 和 asarray() 主要区别就是当数据源是ndarray 时，
# array() 仍然会 copy 出一个副本，占用新的内存，但不改变 dtype 时 asarray() 不会。

x = [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
y = np.array(x)
z = np.asarray(x)
x[1][2] = 2
print(x,type(x))

print(y, type(y))

print(z, type(z))

[[1, 1, 1], [1, 1, 2], [1, 1, 1]] <class 'list'>
[[1 1 1]
 [1 1 1]
 [1 1 1]] <class 'numpy.ndarray'>
[[1 1 1]
 [1 1 1]
 [1 1 1]] <class 'numpy.ndarray'>


### （c）通过fromfunction()函数进行创建

In [50]:
def f(x, y):
    return 10 * x + y
x = np.fromfunction(f, (5, 4), dtype=int)
print(x)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [51]:
x = np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
print(x)

[[ True False False]
 [False  True False]
 [False False  True]]


In [52]:
x = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
print(x)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


### 4.2 特殊数组

In [56]:
### 零数组
x = np.zeros(5)
print(x)
x = np.zeros([2, 3])
print(x)

print('------------------')
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.zeros_like(x)
print(y)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
------------------
[[0 0 0]
 [0 0 0]]


In [57]:
### 1 数组
x = np.ones(5)
print(x)
x = np.ones([2, 3])
print(x)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [58]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.ones_like(x)
print(y)

[[1 1 1]
 [1 1 1]]


In [59]:
# 空数组
# empty() 函数：返回一个空数组，数组元素为随机数
x = np.empty(5)
print(x)
print('------------------')

x = np.empty((3, 2))
print(x)
print('------------------')

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.empty_like(x)
print(y)

[1. 1. 1. 1. 1.]
------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]]
------------------
[[0 0 0]
 [0 0 0]]


### 单位数组

In [61]:
x = np.eye(4)
print(x)
print('------------------')

x = np.eye(2, 3)
print(x)
print('------------------')

# 方阵
x = np.identity(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
------------------
[[1. 0. 0.]
 [0. 1. 0.]]
------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 对角数组

In [63]:
# diag() 函数：提取对角线或构造对角数组。
x = np.arange(9).reshape((3, 3))
print(x)
print(np.diag(x))
print(np.diag(x, k=1))
print(np.diag(x, k=-1))
print('------------------')

v = [1, 3, 5, 7]
x = np.diag(v)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[1 5]
[3 7]
------------------
[[1 0 0 0]
 [0 3 0 0]
 [0 0 5 0]
 [0 0 0 7]]


### 常数数组

In [65]:
x = np.full((2,), 7)
print(x)

x = np.full(2, 7)
print(x)

x = np.full((2, 7), 7)
print(x)

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.full_like(x, 7)
print(y)

[7 7]
[7 7]
[[7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]]
[[7 7 7]
 [7 7 7]]


### 4.3 利用数值范围来创建ndarray
arange() 函数：返回给定间隔内的均匀间隔的值。<br>
linspace() 函数：返回指定间隔内的等间隔数字。<br>
logspace() 函数：返回数以对数刻度均匀分布。<br>
numpy.random.rand() 返回一个由[0,1)内的随机数组成的数组。

In [66]:
x = np.arange(5)
print(x)

x = np.arange(3, 7, 2)
print(x)

x = np.linspace(start=0, stop=2, num=9)
print(x)

x = np.logspace(0, 1, 5)
print(np.around(x, 2))

x = np.linspace(start=0, stop=1, num=5)
x = [10 ** i for i in x]
print(np.around(x, 2))

x = np.random.random(5)
print(x)

x = np.random.random([2, 3])
print(x)

[0 1 2 3 4]
[3 5]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 1.    1.78  3.16  5.62 10.  ]
[ 1.    1.78  3.16  5.62 10.  ]
[0.68787593 0.69970532 0.77620265 0.24974942 0.53305143]
[[0.00415674 0.13839431 0.78597629]
 [0.49904194 0.3704462  0.20404778]]


### 4.4 结构数组的构建

In [70]:
# 利用字典
personType = np.dtype({
    'names': ['name', 'age', 'weight'],
    'formats': ['U30', 'i8', 'f8']})

a = np.array([('Liming', 24, 63.9), ('Mike', 15, 67.), ('Jan', 34, 45.8)], dtype=personType)
print(a, type(a), len(a))

[('Liming', 24, 63.9) ('Mike', 15, 67. ) ('Jan', 34, 45.8)] <class 'numpy.ndarray'> 3


In [69]:
a = np.array([('Liming', 24, 63.9), ('Mike', 15, 67.), ('Jan', 34, 45.8)])
print(a, type(a), len(a))

[['Liming' '24' '63.9']
 ['Mike' '15' '67.0']
 ['Jan' '34' '45.8']] <class 'numpy.ndarray'> 3


In [71]:
# 利用包含多个元组的列表
personType = np.dtype([('name', 'U30'), ('age', 'i8'), ('weight', 'f8')])
a = np.array([('Liming', 24, 63.9), ('Mike', 15, 67.), ('Jan', 34, 45.8)], dtype=personType)
print(a, type(a))

print(a[0])
print(a[-2:])

print(a['name'])
print(a['age'])
print(a['weight'])



[('Liming', 24, 63.9) ('Mike', 15, 67. ) ('Jan', 34, 45.8)] <class 'numpy.ndarray'>
('Liming', 24, 63.9)
[('Mike', 15, 67. ) ('Jan', 34, 45.8)]
['Liming' 'Mike' 'Jan']
[24 15 34]
[63.9 67.  45.8]


## 5 数组的属性

In [72]:
a = np.array([1, 2, 3, 4, 5])
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)
print(a.itemsize)
b = np.array([[1, 2, 3], [4, 5, 6.0]])
print(b.shape)
print(b.dtype)
print(b.size)
print(b.ndim)
print(b.itemsize)

(5,)
int32
5
1
4
(2, 3)
float64
6
2
8


In [73]:
# 在 ndarray 中所有元素必须是同一类型，否则会自动向下转换， int->float->str 
a = np.array([1, 2, 3, 4, 5])
print(a)
b = np.array([1, 2, 3, 4, '5'])
print(b)
c = np.array([1, 2, 3, 4, 5.0])
print(c)

[1 2 3 4 5]
['1' '2' '3' '4' '5']
[1. 2. 3. 4. 5.]


## 6 副本与视图

In [75]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = x
y[0] = -1
print(x)
print(y)

x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = x.copy()
y[0] = -1
print(x)
print(y)

[-1  2  3  4  5  6  7  8]
[-1  2  3  4  5  6  7  8]
[1 2 3 4 5 6 7 8]
[-1  2  3  4  5  6  7  8]


In [81]:
# 切片操作只是返回视图
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = x
y[::2, :3:2] = -1
print(x)
print(y)

x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
y = x.copy()
y[::2, :3:2] = -1
print(x)
print(y)

[[-1 12 -1 14 15]
 [16 17 18 19 20]
 [-1 22 -1 24 25]
 [26 27 28 29 30]
 [-1 32 -1 34 35]]
[[-1 12 -1 14 15]
 [16 17 18 19 20]
 [-1 22 -1 24 25]
 [26 27 28 29 30]
 [-1 32 -1 34 35]]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
[[-1 12 -1 14 15]
 [16 17 18 19 20]
 [-1 22 -1 24 25]
 [26 27 28 29 30]
 [-1 32 -1 34 35]]
