## 13 排序、搜索和计数

### 13.1 排序 

In [3]:
import numpy as np

# axis：排序沿数组的（轴）方向，0表示按行，1表示按列，None表示展开来排序，默认为-1，表示沿最后的轴排序
np.random.seed(20201030)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

y = np.sort(x)
print(y)

y = np.sort(x, axis=0)
print(y)

y = np.sort(x, axis=1)
print(y)

[[6.38 1.89 6.21 5.88 3.69]
 [1.57 3.39 5.61 3.55 2.81]
 [1.58 5.28 7.6  8.47 7.88]
 [6.44 0.86 4.43 1.45 3.49]
 [6.71 9.55 7.78 8.95 0.78]]
[[1.89 3.69 5.88 6.21 6.38]
 [1.57 2.81 3.39 3.55 5.61]
 [1.58 5.28 7.6  7.88 8.47]
 [0.86 1.45 3.49 4.43 6.44]
 [0.78 6.71 7.78 8.95 9.55]]
[[1.57 0.86 4.43 1.45 0.78]
 [1.58 1.89 5.61 3.55 2.81]
 [6.38 3.39 6.21 5.88 3.49]
 [6.44 5.28 7.6  8.47 3.69]
 [6.71 9.55 7.78 8.95 7.88]]
[[1.89 3.69 5.88 6.21 6.38]
 [1.57 2.81 3.39 3.55 5.61]
 [1.58 5.28 7.6  7.88 8.47]
 [0.86 1.45 3.49 4.43 6.44]
 [0.78 6.71 7.78 8.95 9.55]]


In [4]:
dt = np.dtype([('name', 'S10'), ('age', np.int)])
a = np.array([("Mike", 21), ("Nancy", 25), ("Bob", 17), ("Jane", 27)], dtype=dt)
b = np.sort(a, order='name')
print(b)
b = np.sort(a, order='age')
print(b)

[(b'Bob', 17) (b'Jane', 27) (b'Mike', 21) (b'Nancy', 25)]
[(b'Bob', 17) (b'Mike', 21) (b'Nancy', 25) (b'Jane', 27)]


In [7]:
np.random.seed(20200612)
x = np.random.randint(0, 10, 10)
print(x)
# [6 1 8 5 5 4 1 2 9 1]

np.sort(x)
# [1, 1, 1, 2, 4, 5, 5, 6, 8, 9]

y = np.argsort(x)
print(y)
# [1 6 9 7 5 3 4 0 2 8]

print(x[y])
# [1 1 1 2 4 5 5 6 8 9]

y = np.argsort(-x)
print(y)
# [8 2 0 3 4 5 7 1 6 9]

print(x[y])
# [9 8 6 5 5 4 2 1 1 1]

[6 1 8 5 5 4 1 2 9 1]
[1 6 9 7 5 3 4 0 2 8]
[1 1 1 2 4 5 5 6 8 9]
[8 2 0 3 4 5 7 1 6 9]
[9 8 6 5 5 4 2 1 1 1]


In [8]:
np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

y = np.argsort(x)
print(y)

y = np.argsort(x, axis=0)
print(y)

y = np.argsort(x, axis=1)
print(y)

y = np.array([np.take(x[i], np.argsort(x[i])) for i in range(5)])
#numpy.take(a, indices, axis=None, out=None, mode='raise')沿轴从数组中获取元素。
print(y)

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]
[[3 0 4 1 2]
 [1 0 4 2 3]
 [0 2 3 1 4]
 [2 4 1 3 0]
 [1 4 3 2 0]]
[[2 4 2 0 3]
 [0 2 3 2 0]
 [1 3 4 3 4]
 [3 1 1 4 1]
 [4 0 0 1 2]]
[[3 0 4 1 2]
 [1 0 4 2 3]
 [0 2 3 1 4]
 [2 4 1 3 0]
 [1 4 3 2 0]]
[[1.73 2.32 6.22 7.54 9.78]
 [5.17 6.93 8.25 9.28 9.76]
 [0.01 0.19 1.73 4.23 9.27]
 [0.88 4.29 4.97 7.32 7.99]
 [0.07 6.99 7.9  8.95 9.05]]


### 13.2 搜索

In [10]:
np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

y = np.argmax(x)
print(y)

y = np.argmax(x, axis=0)
print(y)

y = np.argmax(x, axis=1)
print(y)

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]
2
[4 0 0 1 2]
[2 3 4 0 0]


In [11]:
np.random.seed(20200612)
x = np.random.rand(5, 5) * 10
x = np.around(x, 2)
print(x)

y = np.argmin(x)
print(y)

y = np.argmin(x, axis=0)
print(y)

y = np.argmin(x, axis=1)
print(y)

[[2.32 7.54 9.78 1.73 6.22]
 [6.93 5.17 9.28 9.76 8.25]
 [0.01 4.23 0.19 1.73 9.27]
 [7.99 4.97 0.88 7.32 4.29]
 [9.05 0.07 8.95 7.9  6.99]]
10
[2 4 2 0 3]
[3 1 0 2 1]


In [12]:
x = np.array([0, 2, 3])
print(x) # [0 2 3]
print(x.shape) # (3,)
print(x.ndim) # 1
y = np.nonzero(x)
print(y) # (array([1, 2], dtype=int64),)
print(np.array(y)) # [[1 2]]
print(np.array(y).shape) # (1, 2)
print(np.array(y).ndim) # 2
print(np.transpose(y))
print(x[np.nonzero(x)])

[0 2 3]
(3,)
1
(array([1, 2], dtype=int64),)
[[1 2]]
(1, 2)
2
[[1]
 [2]]
[2 3]


### 13.3 计数

In [13]:
x = np.count_nonzero(np.eye(4))
print(x)
x = np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]])
print(x)
x = np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]], axis=0)
print(x)
x = np.count_nonzero([[0, 1, 7, 0, 0], [3, 0, 0, 2, 19]], axis=1)
print(x)

4
5
[1 1 1 1 1]
[2 3]


## 14 集合操作

In [14]:
x = np.unique([1, 1, 3, 2, 3, 3])
print(x)

x = sorted(set([1, 1, 3, 2, 3, 3]))
print(x)

x = np.array([[1, 1], [2, 3]])
u = np.unique(x)
print(u)

x = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
y = np.unique(x, axis=0)
print(y)

x = np.array(['a', 'b', 'b', 'c', 'a'])
u, index = np.unique(x, return_index=True)
print(u)
print(index)
print(x[index])

x = np.array([1, 2, 6, 4, 2, 3, 2])
u, index = np.unique(x, return_inverse=True)
print(u)
print(index)
print(u[index])

u, count = np.unique(x, return_counts=True)
print(u)
print(count)

[1 2 3]
[1, 2, 3]
[1 2 3]
[[1 0 0]
 [2 3 4]]
['a' 'b' 'c']
[0 1 3]
['a' 'b' 'c']
[1 2 3 4 6]
[0 1 4 3 1 2 1]
[1 2 6 4 2 3 2]
[1 2 3 4 6]
[1 3 1 1 1]


In [15]:
test = np.array([0, 1, 2, 5, 0])
states = [0, 2]
mask = np.in1d(test, states)
print(mask)
print(test[mask])

mask = np.in1d(test, states, invert=True)
print(mask)
print(test[mask])

[ True False  True False  True]
[0 2 0]
[False  True False  True False]
[1 5]


In [16]:
# 求两个集合的交集
from functools import reduce

x = np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])
print(x)

x = np.array([1, 1, 2, 3, 4])
y = np.array([2, 1, 4, 6])
xy, x_ind, y_ind = np.intersect1d(x, y, return_indices=True)
print(x_ind)
print(y_ind)
print(xy)
print(x[x_ind])
print(y[y_ind])

x = reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
print(x)

[1 3]
[0 2 4]
[1 0 2]
[1 2 4]
[1 2 4]
[1 2 4]
[3]


In [17]:
x = np.union1d([-1, 0, 1], [-2, 0, 2])
print(x)
x = reduce(np.union1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
print(x) 

[-2 -1  0  1  2]
[1 2 3 4 6]


In [18]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
x = np.setdiff1d(a, b)
print(x) 

[1 2]


In [19]:
a = np.array([1, 2, 3, 2, 4, 1])
b = np.array([3, 4, 5, 6])
x = np.setxor1d(a, b)
print(x)

[1 2 5 6]
